### ISSUE TITLE
Не устанавливается продакшн версия

### ISSUE THREAD

**Issue by horeca2** [openpim/server#10]
Пытаюсь установить подакшн версию  согласно инструкции https://openpim.ru/index.html#getstarted
При попытке входа получаю ошибку
![Screenshot_1](https://user-images.githubusercontent.com/56235433/199722136-05869ed1-3248-4960-9650-e901d682837c.png)

Демо версия устанавливается без проблем
В чем может быть проблема?

**Comment by openpim** [comment]
Please take a look at the same issue here - https://github.com/openpim/web/issues/9 
Drop me an email to team@openpim.org please and I will help you
