### ISSUE TITLE
The main image of the product is lost

### ISSUE THREAD

**Issue by horeca2** [openpim/server#12]
In your demo, I click the "Set as main image" button for the second relation in the list, and then restore it as it was. As a result, the main image is lost. And it can't be recovered
![Анимация2](https://user-images.githubusercontent.com/56235433/200672479-c8caae0a-ae65-4e24-864f-98a624afc4e8.gif)

**Comment by horeca2** [comment]
I've tried deleting and reselecting the relationship, with no results. I'm seeing the same problem on the production version

**Comment by horeca2** [comment]
When I press SAVE while editing a TYPE I get this in the console. Even if no type properties are changed 
![2022-11-09_00-49-40](https://user-images.githubusercontent.com/56235433/200683334-05d65637-54dc-4133-86cb-a0fba5993cee.png)

**Comment by openpim** [comment]
loosing of main image is know issue, we will work on this. You can reload a model now as a workaround. You should login as admin, then click user profile button and then reload model
![image](https://user-images.githubusercontent.com/71308573/200758370-90948ad6-e3d7-4942-b76f-a266cbf6419a.png)
And main image should appear again after this.

**Comment by horeca2** [comment]
> loosing of main image is know issue, we will work on this. You can reload a model now as a workaround. You should login as admin, then click user profile button and then reload model ![image](https://user-images.githubusercontent.com/71308573/200758370-90948ad6-e3d7-4942-b76f-a266cbf6419a.png) And main image should appear again after this.

Thank you, I did as you said and the image was restored

**Comment by openpim** [comment]
fixed, please pull new image with version 1.5
