### ISSUE TITLE
Error creating object after type creation

### ISSUE THREAD

**Issue by horeca2** [openpim/server#13]
I created a new type, then I immediately create a new object based on that type. Nothing works. See the bug demo.

The problem is solved by refreshing the page.
![Анимация2](https://user-images.githubusercontent.com/56235433/200687358-1e9bea55-7a82-433b-a7b1-adf66ef14cfa.gif)

**Comment by horeca2** [comment]
I noticed some other bugs but haven't been able to reproduce them yet, are you interested in getting feedback?

**Comment by openpim** [comment]
ok, we will work on this. Regarding the issues that is difficult to reproduce better to avoid posting them because we will not be able to work on this if we can not reproduce it.

**Comment by horeca2** [comment]
![dfdfd](https://user-images.githubusercontent.com/56235433/201072064-cbe5ae90-e720-494b-9917-6cc6256de70c.gif)

Here is another similar error when trying to use a newly created relation.

**Comment by openpim** [comment]
it is recommended to refresh the page after changing of the data model to avoid such issues.
Low low priority, we will fix this if we have time in future.
