### ISSUE TITLE
Incorrect behavior of the "Relations" tab

### ISSUE THREAD

**Issue by horeca2** [openpim/server#14]
Incorrect behavior of the "Relations" tab when refreshing the page in the browser. The name of the relation in the list is not correct
![Анимация3](https://user-images.githubusercontent.com/56235433/200691179-dac79590-85f8-41bc-8e5e-f1543eb1b72a.gif)

**Comment by openpim** [comment]
ok, we will fix this

**Comment by openpim** [comment]
fixed, please pull new image with version 1.5
