### ISSUE TITLE
Can't see error when saving attribute

### ISSUE THREAD

**Issue by horeca2** [openpim/server#16]
If, when creating an attribute, I forget to fill in a required field, such as type, and then click the save button, the empty field is highlighted in red. But if the screen is scrolled down, then this field is not visible, then I do not see this error and I think that the attribute was successfully saved, although it was not. Maybe add an error popup?

This happens to other entities besides the attribute as well. It’s bad that having made such a mistake, I can go to the WORK tab where for some reason I see these unsaved entities and can select them, at this moment additional errors appear. Please don't show unsaved entities on WORK

**Comment by openpim** [comment]
low priority, we will change UI if we have time in future
