### ISSUE TITLE
can't delete images and relationships

### ISSUE THREAD

**Issue by horeca2** [openpim/server#17]
![Анимация22](https://user-images.githubusercontent.com/56235433/201104153-d5990b01-8834-43ed-b8e3-1f26f556a45c.gif)
I deleted several relationships and something went wrong. After that, I can't delete images and one relationship that doesn't seem to be related to images.

In addition, I lost the ability to edit the product type. But I can no longer demonstrate because I have already removed this type

If you want, I can open access to the server so you can check

**Comment by openpim** [comment]
we have checks to avoid the deletion of relation when it is using somewhere, but maybe we still have a case when the relation can be deleted when it is still used somewhere. 

You can go directly to the database and delete wrong data there. The database structure is easy. All objects are in "items" table, all relations are in "itemRelations" table.
