### ISSUE TITLE
openpim server rest api?

### ISSUE THREAD

**Issue by shahartal80** [openpim/server#18]
Hi,

Looks like a great product! does the server have a rest api for integrations?

Thanks!
Shahar

**Comment by openpim** [comment]
Hi @shahartal80,

We have rich  GraphQL API in our system. It is not documented well yet, but you can see GraphQL schemas of api in our server sources https://github.com/openpim/server/tree/master/schema.

If you want we can organize a call where I can show this to you in more details. Just drop me an email at team@openpim.org
