### ISSUE TITLE
Accessing Data for anonymous users

### ISSUE THREAD

**Issue by jfayad** [openpim/server#27]
According to the test we ran so far, it is a requirement to have a valid token in order to have read access to the PIM data.
The same also applies for assets (ie images, docs etc...)

The documentation on that side doesn't carry much details, I would like to confirm the understanding I have and also ask if there's any other way available to open up access to certain data to the "outside world" ?

Is there any reason not to use the PIM as a API to populate data on website ?

**Comment by openpim** [comment]
Hi,

You can set the option directUrl=true to your type in data model that represent the image or file and you will be able to access it without token
![image](https://github.com/user-attachments/assets/1b890e13-3431-445b-a944-a1a9e9fcd6a1)
