### ISSUE TITLE
Error: EXDEV: cross-device link not permitted, rename

### ISSUE THREAD

**Issue by kormilec** [openpim/server#3]
Error when upload images error.log
1. run
docker run -d -p 80:80 -v /home/myproject/cdn:/filestorage --env OPENPIM_DATABASE_ADDRESS=localhost --env OPENPIM_DATABASE_NAME=pim --env OPENPIM_DATABASE_USER=user --env OPENPIM_DATABASE_PASSWORD=password openpim/russian:1.4
2. upload image
3. Error: EXDEV: cross-device link not permitted, rename

**Comment by openpim** [comment]
Hi @kormilec,

This is not an error, this is more wrong message. We are trying to use rename file first to put the uploaded file to our storage and when this is not possible (for example you have different filesystems where you are uploading the file and where files are stored) then we are using copy file. So we had an error message there by mistake. Functionality itself is working right.
I've uploaded new version where this error message is removed. You should pull new image from docker and use it to avoid this.

Thanks
