### ISSUE TITLE
Loading a product with all its variants in one query

### ISSUE THREAD

**Issue by mahfouzhseineweev** [openpim/server#30]
In a product list page, we have a requirement to show different colors **product variants** for each product, and so far the only way we found is to call the getItems for every product in the list. 

But this will impact the performance of the page as there will be multiple products that we will be required to run the getItems for each one of them.

I have 2 questions:

1) We have been searching for a way to load a product and all of its variants in a one single query, but we couldn't find one so I am wondering if we missed something the docs that could help solving this problem ?

2) Is there a way to have nested objects structure returned in the response for the getItemByIdentifier query as an example ?

Something like:

```JSON
{
 "colors": {
     "body_color":  {
            "name": "white",
            "code": "#FFF"
      },
      etc...
 }
}
```

**Comment by openpim** [comment]
Hi, 

If I understand right you are talking about the ability to receive the data by API and not by changing colors in the web UI of the system itself. Right?

In this case you can use search API - https://github.com/openpim/server/blob/master/schema/search.graphql that can return list of objects by some query. For example, you can query the object itself and all it children. Something like this:

query { search(
        requests: [
            {
                entity: ITEM, 
                offset: 0, 
                limit: 100,
                where: {OP_or: [{identifier: "object_identifier"}, {parentIdentifier: "object_identifier"}] }
            }
            ]
        ) {
        responses {
            ... on ItemsSearchResponse {
                count
                rows {
                    identifier
                    name
                    parentIdentifier
                    values
                }
            }
        }}}   

so here we are receiving the object with identifier: "object_identifier" and also all objects that has parent object also with such identifier in one list.

We can also organize a call if you want where we can discuss our query language in more details and found the way that is working for you. This query language is not documented well yet :(

**Comment by mahfouzhseineweev** [comment]
Hello,

I have tried following the example, but the result I got is not what we need. I could have run the getItems query using the parentId to get the list of products.

However as seen in the screenshot below, what we need is to get the list of products using `standing_lamps` identifier (because at this stage, only this identifier is known) so `La Lampe Padère M` and `La Lampe Padère S`.
And also have the colors variants also returned for each product using the same query

<img width="877" alt="image" src="https://github.com/user-attachments/assets/dc3d0b06-3d09-4ea6-af66-1b5332f69327">

**Comment by openpim** [comment]
Hi,

ok, now it is more clear. In this case we can use another approach. We have ability to query by tree structure. In this case you should know internal id (not identifier that is usually some external id). Each object has it and you can query it by API the same as identifier ("id" field). This is a number. 

And we have a "path" field also in each object. That stores all tree path. For example, if your "standing_lamps" has id=1 and "La Lampe Padère M" has id 2, them "La Lampe Padère M" will have a path "1.2" and so on. For example, if "Green - Black" has id=3 then it will have path "1.2.3". You can see this in the database, table "items", column "path".

So this means that we always have all tree path in each object and we can query it by API. Again, if your "standing_lamps" has id=1 then you can query all it subtree by 

{where: {path:{OP_regexp:"*.1.*"}}}

this means find all object that has such path template. As result you will receive all subtree as a list. But you will also has a parentIdentifier in all objects, so you can restore this subtree from the list.

Hope this helps.

**Comment by mahfouzhseineweev** [comment]
Now even though we have in the response array the category itself `standing_lamps` and even if the children are not returned in a correct order, we can do a mapping on the frontend to have a list of the products and there variants. So the solution worked, but the getting the assets per product is another problem introduced:

1. There is one last problem, that is the assets of the products, like for `La Lampe Padère S` and `La Lampe Padère M`. We will be required to wait for the response of the search query and then run a getAssets query for each product in the listing to have there images which wont be efficient. Is there a way to return them using the search query ?

2) Quick question: Is there a way to have nested objects with arrays structure returned in the response for the getItemByIdentifier query as an example ?

Something like:

```JSON
{
   "specs":{
      "colors": [
         {
            "body_color":{
               "name":"white",
               "code":"#FFF"
            }
         },
         {
            "cadre_color":{
               "name":"white",
               "code":"#FFF"
            }
         },
         etc...
      ],
      etc...
   }
}
```

**Comment by openpim** [comment]
Hi @mahfouzhseineweev,

We decided not to give the ability to receive nested strictures to avoid performance problems. But usually we can receive all that is necessary by one search query. Can you please clarify what exactly you want to receive? List of images attached to the product?

What do you need from image? Just image url? Or image details like name, resolution, etc? Because if you want to receive URL you just need an image "id"  and this is easy to receive by search request for relations. If you want to receive image details, then this is more complicated, but also possible (we have ability to use join in search, for example find all images that are linked to the product.)

Can you please describe in more details what data model you have now and what you want to receive?

**Comment by openpim** [comment]
by the way, you can also define the order of returned query

> query { search(
>    requests: [
>    {
>       entity: ITEM,
>       offset: 0,
>       limit: 100,
>       where: {where: {path:{OP_regexp:"*.1.*"}}},
> 	  order:[["id","ASC"]]
>    }
> ]
> ) {
> responses {
> ... on ItemsSearchResponse {
>    count
>    rows {
>       identifier
>       name
>       parentIdentifier
>       values
>    }
> }
> }}}

In this case order is by ID that is autogenerated, so parent will be always first (before children) in the list and this will help with building a tree from the list

**Comment by mahfouzhseineweev** [comment]
Hello,

Thank you for the notice about the order and noted for the nested structure.

Basically each product have a main image that should show in the list of products, for example we can use the id of the image `ID: 136` like this `http://openPIMURL/asset/136` to preview it.

In the example screenshot below:

We have 2 products in the listing of `Standing Lamps`:  `La Lampe Padère S` and `La Lampe Padère M` each product has a main image like `variant image 1.jpg`.

What we need is to have at least the ID of the image returned in the search response for each main product so we can preview it ex.: Main image for `La Lampe Padère S` and `La Lampe Padère M`. Also it would be helpful if we have a list of Images IDs if there are multiple ones for each product.

<img width="511" alt="image" src="https://github.com/user-attachments/assets/28ad245e-10f0-4420-bb4e-329ff8bf2727">

**Comment by openpim** [comment]
Hi @mahfouzhseineweev,

In such case you can use relations search, for example we can find all relations that has identifiers "mainImage" or "images" for the products with identifiers "Lampe_Padere_S" or "Lampe_Padere_M"

query { search(
        requests: [
            {
                entity: ITEM_RELATION, 
                offset: 0, 
                limit: 100,
                where: {relationIdentifier: {OP_in:["mainImage", "images"]}, itemIdentifier: {OP_in: ["Lampe_Padere_S","Lampe_Padere_M"]}},
                order: [["id", "ASC"]]
            }
            ]
        ) {
        responses {
            ... on SearchItemRelationResponse  {
                count
                rows {
                    identifier
                    itemIdentifier
                    itemId
                    targetIdentifier
                    targetId
                }
            }
        }}}   

You will have targetId in response, this is an id of image and you can build the URL from it

**Comment by mahfouzhseineweev** [comment]
Hi @openpim ,

The ITEM_RELATION query in this case will be made for every entry of the previous Search query that returned all the products and there variants.

What we have now to get the products list and there variants is using this query that only takes the ID of the category **(64)** for the path which is working fine but still missing the images of the main products:

```graphql
query Search {
    search(
        requests: {
            entity: ITEM
            where: {
                        path: { OP_regexp: "*.64.*" }
                        typeIdentifier: { OP_or: ["variant", "product"] }
                    }
            offset: 0
            limit: 100
        }
    ) {
        responses {
            ... on ItemsSearchResponse {
                count
                rows {
                    id
                    path
                    identifier
                    parentIdentifier
                    name
                    typeId
                    typeIdentifier
                    values
                    channels
                    mimeType
                    fileOrigName
                    createdBy
                    createdAt
                    updatedBy
                    updatedAt
                }
            }
        }
    }
}
```

I am wondering if there is a way by updating the same query I shared to have for example the `targetId` for each product that is the ID of its image, or a list of IDs of this product images if it is a list ?

**Comment by openpim** [comment]
Hi @mahfouzhseineweev,

You should not perform the item relation query to each product. You can collect product ids from item query and then send item relation query with list of ids 

`{itemId: {OP_in: [...]}}`

so you will receive all images for the list of items. Yes, "IN" operation in DB has limitations, but we used it for thousands ids without any problem.

There is also an ability to make a query with join, like "find all relations that has a link to item that have path like this". But this will  add the complexity. I think list of ids for relation query will works fine.

**Comment by mahfouzhseineweev** [comment]
Thank you for your help, that was it. We will go for the solution of running the Search query on the ITEM entity and one other Search query on the ITEM_RELATION with the list of products ids `{itemId: {OP_in: [...]}}`
