### ISSUE TITLE
graphQL Subscription or webhook

### ISSUE THREAD

**Issue by jfayad** [openpim/server#31]
I couldn't find any information about a subscription or a webhook in place to be notified whenever some data is being updated in OpenPIM.

I checked in both the documentation and the Postman collection.

I currently need to know when an item is added/edited/deleted and when LOVs are being modified. is anything of that sort in place ? If yes where could I find some documentation about it ?

**Comment by openpim** [comment]
Hi @jfayad,

There is not such ability on the API.
But you can define an action. This is addition logic that is executed on some trigger in the server. So there you can react on the changes and call rest API for example.

We do not have ready documentation yet for the actions, but you can take a look at the example on our demo - http://demo.openpim.org/#/login?user=demo&password=demo

There is the example of such action - https://demo.openpim.org/#/config/actions/attrChange
