### ISSUE TITLE
How to set a default language in Open pim ? 

### ISSUE THREAD

**Issue by akramsarkis** [openpim/server#36]
- [ ] I would like to set a default language for open pim but when accessing Languages under Settings I have no way to do so, can you please help me ?

Thanks

**Comment by openpim** [comment]
Hi @akramsarkis,

You are right there is no way now to set default language. Now system is taking first language as default. First means the language with less id in the database in the "languages" table. So to resolve this temporally you should modify this table in database and put necessary language first. We will add the ability to configure this but it will take some time

**Comment by akramsarkis** [comment]
Ok thank you for your answer
