### ISSUE TITLE
Setting a field as required

### ISSUE THREAD

**Issue by akramsarkis** [openpim/server#37]
- [ ] I have searched how I can put an attribute as required but without success
- I checked if for the attribute there is such option but I am not seeing one
- I tried to do research to use the Options section but as well I did not find something that helps

Can you please give me advice? Thanks for your help

**Comment by akramsarkis** [comment]
> Hi @akramsarkis,
> 
> Required can have different meaning for different projects, for example, you can not save the object without some field (this is the easiest case). But disabling the save option can be not good option. Sometimes you want to allow to temporary save the data, but you will not allow to export such object that has not enough data. So we did not make ready "required" functionality.
> 
> But you can use actions - https://openpim.org/university/actions/ to make any logic you want.
> 
> For example, if you have an attribute with identifier "sku" you can write easy action and put it to BeforeUpdate trigger:
> 
> if (!values.sku) throw new Error('SKU is empty')
> 
> As result, if user will try to save the object without "sku" attribute he will receive the error

Hello @openpim ,

I have tried this but was not able to reach what I need , I added the action you mentioned if (!values.sku) throw new Error('SKU is empty') when I goes to Trigger I have several choices like you can see below, I selected Item changing

<img width="571" alt="Screenshot 2024-11-14 at 09 49 14" src="https://github.com/user-attachments/assets/b39f0e1e-4bf5-44ea-afef-653b56645837">

Then from the below choices I tried before create, before update, after create but without success , what is the correct trigger and then option to select to have the message showing after I create the item and then I click on save without entering any attribute value starting by SKU ? 

But my problem is that I need it on barecode that is a value like this one 3089850010015 name of the field is  Bar code and identifier is barecode

**Comment by openpim** [comment]
You should attach this action to Item changing and before update. So you will have "values" object with new data that is going to be updated. Please take a look at https://openpim.org/university/actions/
