### ISSUE TITLE
Avoid race condition on updates

### ISSUE THREAD

**Issue by jfayad** [openpim/server#38]
Hello,

This question is more about knowing the correct approach to a common use case, it could probably serve as best practice for other users...

I am using OpenPIM to store the product catalog of an eCommerce website, the inventory seats in a warehouse which sends us a daily report of stock levels for each item.

When this is received, I need to update the stock quantity in OpenPim (it's a regular field in an item).

My main concern is about race conditions, I need to read the item from Open PIM, compute the correct qty based on items data and then update the item's qty field.

In between the read and the write, I might have a user interacting with the system in a way that would update the field I use to compute the new qty, which would lead to an outdated value inserted during the write.

A naive approach would be to set a DB lock on the row of the item before reading it, and releasing the lock after the update is done but that means I'll need to run 3n queries for n items to update (1 to lock, 1 to read and 1 to write) instead of running n+1 queries (1 to read all items, 1 to write each item). As putting a lock on the whole table might slow down many mutations...

I'm wondering if there's a better approach when using the API that took that into consideration when updating item(s) ?
I saw something about Process in the API, but it's not documented, so I'm wondering if that could be a solution to the above problem ?

If not, do you have any suggestion ?

Thank you

**Comment by jfayad** [comment]
Hi @openpim 

Thank you for the reply.
Using db lock also means I would have to perform the update on my own code (with direct db access) as part of the transaction that is locking the row as the API call will use a different DB connection that would be locked... Is this fine ?

Optimistic locking is NOT fine in this particular case as I don't want to allow any change to be performed while I run this transaction

**Comment by openpim** [comment]
Hi, yes, here you should use direct DB access. 
But I did not realized that you should perform some calculations... In this case you can also move the calculation to the server side logic. You can create an action https://openpim.org/university/actions/ that will be triggered by BeforeUpdate event and then you will be able to calculate all necessary during product update

**Comment by jfayad** [comment]
Using actions is an interesting approach but it doesn't really solve the problem I have.

By locking the DB on the read I have to perform the update within the same DB transaction.
If I use the API to perform the update, it will run in another transaction and my initial lock will prevent the update from happening, creating a deadlock.

I have to actually update the record in DB directly in my app. I'm making sure to also update the updatedAt field too (is there any other field I should worry about ?).
I'm well aware that doing that will shortcircuit any trigger/action etc... but that's the only viable solution I have now.
