### ISSUE TITLE
How to use PIM for car service 

### ISSUE THREAD

**Issue by alaamh** [openpim/server#4]
Thank you for the wonderful work.

For car service, I'm trying to apply the nice design you have maid with the data model concept on brand, catalog, category, price, and product.

So please correct me, category, and product will be types and price will a separate type and relation defined between product and price type then brand and channel will be attributes. where to configure catalog (group of products), and how to add associated products? like related product, is spare part of, similar, etc..

**Comment by openpim** [comment]
Hi Aladdin,

There is no only one right way to build a data model. This depends from business requirements itself (our system does not limit you).
Price can be just a attribute (or several attributes for several price types) in easy scenarios. But it can be also be a separate entity with the link to the product entity if you want to apply addition attributes to price itself (like currency or time of validity, etc).

Brand is the same. If you have just a Brand name it can be an attribute, but if the Brand data is more complex and has mode attributes, I would make it also as s separate entity. For example, you can have brand description, country, etc. You can even have brand logos, images or other documents attached to the brand. So it is quite often that brand is a separate entity too.

I am not fully sure what do you mean under channels. We have also channel notation in the system, but this is more for data export.

Regarding the product associations this also can be a relation between products. Usually we are using them for such associations like spare part of, similar, etc..

Thanks,
Slava Pedak
