### ISSUE TITLE
I need to have a attribute only editable for a specific role is this possible ?

### ISSUE THREAD

**Issue by akramsarkis** [openpim/server#40]
- [ ] I need to have a attribute only editable for a specific role is this possible ? If yes can you please let me know the steps. Thank you

Regarding the documentation doing the configuration below for a role should restrict the access to the attributes, so here we set for the open pim user role the stick attribute group to read only but even though with a user having this role we are able to edit the stock attribute group

<img width="1216" alt="Screenshot 2024-11-13 at 18 18 34" src="https://github.com/user-attachments/assets/8bc929cf-b08d-4b7f-ace4-fb36783122c4">

**Comment by openpim** [comment]
we are working now at the documentation that will describe roles. Hope it will be ready soon.

In you case, it is important to set also Restrictions for Types and Starting from. You you should define to what object (type) you want to apply this configuration and also the hierarchy from what to apply this (the same as we have for attribute).
So attribute configuration here is working only with type+hierarchy

**Comment by akramsarkis** [comment]
> we are working now at the documentation that will describe roles. Hope it will be ready soon.
> 
> In you case, it is important to set also Restrictions for Types and Starting from. You you should define to what object (type) you want to apply this configuration and also the hierarchy from what to apply this (the same as we have for attribute). So attribute configuration here is working only with type+hierarchy

Hello @openpim ,

Thank you for you answer.

To have it work I have done the below:

1) Access as Admin the Role I want to configure then the Data table
2) For types I added restrictions on my type Product
3)For Starting from I have selected my whole store
4) For the access I set it as Full access
5) For restrictions for attributes I added one fo the Stock group to be read only and I saved

<img width="876" alt="Screenshot 2024-11-14 at 16 07 53" src="https://github.com/user-attachments/assets/f65259fb-6725-4923-ab3d-211d93cfe03a">
