### ISSUE TITLE
Dependency Upgrade

### ISSUE THREAD

**Issue by alaamh** [openpim/server#5]
Is there any plan to upgrade the package dependencies specially the migration from GraphQL import.
[Refe](https://www.graphql-tools.com/docs/migration/migration-from-import#migration-from-graphql-import)

**Comment by alaamh** [comment]
I have upgraded the dependency, I will commit to a new branch.

**Comment by openpim** [comment]
Hi @alaamh,

Yes, we have a plan to upgrade package dependencies, for example we still waiting  when Vuetify will have vue 1.3 support. But this task is not high priority. So thanks a lot for your contribution, maybe you can submit it as a change request?

Thanks,
Slava Pedak

**Comment by alaamh** [comment]
Sure, I have tried to push but got below error:
`remote: Permission to openpim/server.git denied to alaamh`

**Comment by openpim** [comment]
yes, direct push is not supported. You can create a pull request —  https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request  or maybe you can simple send me changed files to  ***@***.***  and I will merge them myself.
 
Thanks,
Slava Pedak

**Comment by alaamh** [comment]
Thanks, I have followed the steps by create a fork then create a change request [#6](https://github.com/openpim/server/pull/6)

**Comment by openpim** [comment]
Thanks a lot! I will test it and push to the sources.
 
Thanks,
Slava Pedak
