### ISSUE TITLE
Can't use SSL with Postgres

### ISSUE THREAD

**Issue by steventt07** [openpim/server#7]
Hi!

While testing your tool, I notice there wasn't an option to enable ssl for Postgres db connections. The database I am using requires ssl. Is there anyway to add an ssl option as an environment variable to enable this?

**Comment by openpim** [comment]
Hi @steventt07,

You are right, it is not possible for now. We will add such ability this week. I will let you know when it is ready.

Thanks

**Comment by steventt07** [comment]
Great!

Will this change be pushed to the latest version of your docker image?

Thanks

**Comment by openpim** [comment]
New docker image is created.

Now you can provide parameter like --env OPENPIM_DATABASE_OPTIONS={"application_name":"OpenPIM"}

OPENPIM_DATABASE_OPTIONS is a json object with parameters described here - https://sequelize.org/docs/v6/other-topics/dialect-specific-things/#postgresql

so you can define SSL connection option.

Please let me know if this is not working for you.

Thanks

**Comment by steventt07** [comment]
Hi

It is not working as expected. I am getting this error

`2022/05/19 17:21:47.420 [info]:  Server version: 1.5.220519487
2022/05/19 17:21:47.424 [info]:  Arguments: /usr/local/bin/node,/server/dist/src/index.js
undefined:1
{application_name:OpenPIM}
 ^

SyntaxError: Unexpected token a in JSON at position 1
    at JSON.parse (<anonymous>)
    at initModels (/server/dist/src/models/index.js:51:31)
    at /server/dist/src/index.js:69:35
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022/05/19 17:21:47.420 [info]:  Server version: 1.5.220519487
2022/05/19 17:21:47.424 [info]:  Arguments: /usr/local/bin/node,/server/dist/src/index.js
undefined:1
{application_name:OpenPIM}
 ^

SyntaxError: Unexpected token a in JSON at position 1
    at JSON.parse (<anonymous>)
    at initModels (/server/dist/src/models/index.js:51:31)
    at /server/dist/src/index.js:69:35
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

I believe the issue stems from this issue, https://stackoverflow.com/questions/14432165/uncaught-syntaxerror-unexpected-token-with-json-parse.

Thanks

**Comment by openpim** [comment]
You provided not valid JSON as parameter. JSON should be {"application_name":"OpenPIM"} (with double quotes)

**Comment by steventt07** [comment]
Ah gotcha, thanks fort the clarification.
