### ISSUE TITLE
SSO Integration

### ISSUE THREAD

**Issue by steventt07** [openpim/server#9]
Hi,

Is there any plans to add SSO integrations for login?

Thanks!

**Comment by openpim** [comment]
Hi, we have plans to integrate with Active Directory Federation Services. This can be ready in 1-2 months.

What SSO is you are interested in?

Thanks,
Slava Pedak

**Comment by steventt07** [comment]
Hi,

That is great to hear. I am looking for SAML authentication for SSO.

Thanks!

**Comment by steventt07** [comment]
Hello,

Any updates on this?

Thanks!

**Comment by openpim** [comment]
Hi @steventt07,

We have first example of AD (Active Directory) integration. The idea is that system can check login/password against AD and create an external user in the system on the fly.

Please take a look at example at https://github.com/openpim/modules/tree/main/ad_integration

Also please do not forget to make "docker pull openpim/production:1.5" to refresh your system version.

This is not SAML authentication, so we do not redirect the user to the external login page. We are using our login page but the authentication is going against external source. If you are using not AD you can change a little code of this example to authenticate users against other sources. The logic of authentication (you check user/password and return an object with user details if authentication was successful) and deployment to the server will be the same.

Thanks,
Slava Pedak

**Comment by openpim** [comment]
closing this because we have example of AD integration now
